### ISSUE TITLE
error

### ISSUE THREAD

**Issue by forliuyifei** [glazec/hexo-cheatsheets#20]
```
ERROR {
  err: OperationalError: Undefined variable: "$base-body".
      at options.error (/data/data/com.termux/files/home/py.loafing.cn/node_modules/node-sass/lib/index.js:291:26) {
    cause: Error: Undefined variable: "$base-body".
        at options.error (/data/data/com.termux/files/home/py.loafing.cn/node_modules/node-sass/lib/index.js:291:26) {
      status: 1,
      file: '/data/data/com.termux/files/home/py.loafing.cn/themes/cheatsheets/source/sass/2017/base/base.scss',
      line: 7,
      column: 15,
      formatted: 'Error: Undefined variable: "$base-body".\n' +
        '        on line 7 of themes/cheatsheets/source/sass/2017/base/base.scss\n' +
        '>>   background: $base-body;\n' +
        '\n' +
        '   --------------^\n'
    },
    isOperational: true,
    status: 1,
    file: '/data/data/com.termux/files/home/py.loafing.cn/themes/cheatsheets/source/sass/2017/base/base.scss',
    line: 7,
    column: 15,
    formatted: 'Error: Undefined variable: "$base-body".\n' +
      '        on line 7 of themes/cheatsheets/source/sass/2017/base/base.scss\n' +                                               '>>   background: $base-body;\n' +                            '\n' +                                                        '   --------------^\n'                                    }                                                           } Asset render failed: %s sass/2017/base/base.css             ERROR {                                                         err: OperationalError: Undefined variable: "$shadow6".            at options.error (/data/data/com.termux/files/home/py.loafing.cn/node_modules/node-sass/lib/index.js:291:26) {            cause: Error: Undefined variable: "$shadow6".                     at options.error (/data/data/com.termux/files/home/py.loafing.cn/node_modules/node-sass/lib/index.js:291:26) {            status: 1,                                                    file: '/data/data/com.termux/files/home/py.loafing.cn/themes/cheatsheets/source/sass/2017/components/announcements-item.scss',
      line: 6,
      column: 17,
      formatted: 'Error: Undefined variable: "$shadow6".\n' +
        '        on line 6 of themes/cheatsheets/source/sass/2017/components/announcements-item.scss\n' +
        '>>     box-shadow: $shadow6;\n' +
        '\n' +
        '   ----------------^\n'
    },
    isOperational: true,
    status: 1,
    file: '/data/data/com.termux/files/home/py.loafing.cn/themes/cheatsheets/source/sass/2017/components/announcements-item.scss',
    line: 6,
    column: 17,
    formatted: 'Error: Undefined variable: "$shadow6".\n' +
      '        on line 6 of themes/cheatsheets/source/sass/2017/components/announcements-item.scss\n' +
      '>>     box-shadow: $shadow6;\n' +
      '\n' +
      '   ----------------^\n'
  }
} Asset render failed: %s sass/2017/components/announcements-item.css
ERROR {
  err: OperationalError: no mixin named gutter
      at options.error (/data/data/com.termux/files/home/py.loafing.cn/node_modules/node-sass/lib/index.js:291:26) {
    cause: Error: no mixin named gutter
        at options.error (/data/data/com.termux/files/home/py.loafing.cn/node_modules/node-sass/lib/index.js:291:26) {
      status: 1,
      file: '/data/data/com.termux/files/home/py.loafing.cn/themes/cheatsheets/source/sass/2017/components/body-area.scss',
      line: 2,
      column: 12,
      formatted: 'Error: no mixin named gutter\n' +                   '        on line 2 of themes/cheatsheets/source/sass/2017/components/body-area.scss\n' +                                    '>>   @include gutter(padding);\n' +                          '\n' +                                                        '   -----------^\n'                                       },                                                            isOperational: true,                                          status: 1,                                                    file: '/data/data/com.termux/files/home/py.loafing.cn/themes/cheatsheets/source/sass/2017/components/body-area.scss',       line: 2,                                                      column: 12,                                                   formatted: 'Error: no mixin named gutter\n' +                   '        on line 2 of themes/cheatsheets/source/sass/2017/components/body-area.scss\n' +                                    '>>   @include gutter(padding);\n' +                          '\n' +
      '   -----------^\n'
  }
} Asset render failed: %s sass/2017/components/body-area.css
ERROR {
  err: OperationalError: Undefined variable: "$base-mute".
      at options.error (/data/data/com.termux/files/home/py.loafing.cn/node_modules/node-sass/lib/index.js:291:26) {
    cause: Error: Undefined variable: "$base-mute".
        at options.error (/data/data/com.termux/files/home/py.loafing.cn/node_modules/node-sass/lib/index.js:291:26) {
      status: 1,
      file: '/data/data/com.termux/files/home/py.loafing.cn/themes/cheatsheets/source/sass/2017/components/back-button.scss',
      line: 18,
      column: 12,
      formatted: 'Error: Undefined variable: "$base-mute".\n' +
        '        on line 18 of themes/cheatsheets/source/sass/2017/components/back-button.scss\n' +
        '>>     color: $base-mute;\n' +
        '\n' +
        '   -----------^\n'
    },
    isOperational: true,
    status: 1,
    file: '/data/data/com.termux/files/home/py.loafing.cn/themes/cheatsheets/source/sass/2017/components/back-button.scss',
    line: 18,
    column: 12,
    formatted: 'Error: Undefined variable: "$base-mute".\n' +
      '        on line 18 of themes/cheatsheets/source/sass/2017/components/back-button.scss\n' +
      '>>     color: $base-mute;\n' +
      '\n' +
      '   -----------^\n'
  }                                                           } Asset render failed: %s sass/2017/components/back-button.cssERROR {
```

**Comment by glazec** [comment]
Any more details？Can you provide the corresponding markdown file ?
